import type { Tenant } from '../index';
import { dailyHours } from '../index';
import type { SlotId } from './layout';

/**
 * Demo directory content. Recognisable brand names are used for visual familiarity only;
 * all copy is generic demo text and does not imply any commercial relationship.
 */
export interface DemoTenant {
  id: string;
  name: string;
  categoryId: string;
  subcategory: string;
  floorId: 'l0' | 'l1' | 'l2';
  slot: SlotId;
  unitNumber: string;
  anchor?: boolean;
  brandColor: string;
  logo?: string;
  heroImage?: string;
  shortSummary: string;
  description: string;
  keywords: string[];
  productTypes: string[];
  services: string[];
  brands?: string[];
  hours?: Tenant['hours'];
  accessibilityNotes?: string;
  dining?: Tenant['dining'];
  cinema?: Tenant['cinema'];
  status?: Tenant['status'];
  hi?: { name?: string; shortSummary?: string };
}

const cafe = dailyHours('08:30', '22:30', { open: '08:30', close: '23:30' });
const dining = dailyHours('11:00', '22:30', { open: '11:00', close: '23:30' });
const demoUrl = (id: string, page: string) => `https://example.com/riverside/${id}/${page}`;

export const demoTenants: DemoTenant[] = [
  /* ---------------------------- L0 · Entrance & Essentials ---------------------------- */
  {
    id: 'marks-spencer',
    name: 'Marks & Spencer',
    categoryId: 'fashion',
    subcategory: 'Department store',
    floorId: 'l0',
    slot: 'TL',
    unitNumber: 'L0-01',
    anchor: true,
    brandColor: '#1f2a24',
    shortSummary: 'Clothing, lingerie, home essentials and a British food hall.',
    description:
      'A two-level department store with smart workwear, everyday basics, lingerie and a curated food hall of biscuits, chocolates and pantry treats.',
    keywords: [
      'department store',
      'clothes',
      'clothing',
      'workwear',
      'lingerie',
      'formal',
      'men',
      'women',
      'kids clothes',
      'food hall',
    ],
    productTypes: ['Womenswear', 'Menswear', 'Lingerie', 'Kidswear', 'Food hall'],
    services: ['Alterations', 'Gift cards', 'Click & collect'],
    brands: ['Autograph', 'Per Una'],
  },
  {
    id: 'starbucks',
    name: 'Starbucks',
    categoryId: 'dining',
    subcategory: 'Coffee shop',
    floorId: 'l0',
    slot: 'T1',
    unitNumber: 'L0-02',
    brandColor: '#00704a',
    heroImage: '/demo/stores/starbucks.webp',
    shortSummary: 'Handcrafted coffee, cold brews and bakery bites.',
    description:
      'Espresso classics, seasonal lattes, cold brew and freshly baked pastries — a quick stop right by the main entrance.',
    keywords: ['coffee', 'cafe', 'latte', 'espresso', 'cold brew', 'tea', 'breakfast', 'wifi'],
    productTypes: ['Coffee', 'Cold drinks', 'Bakery', 'Sandwiches'],
    services: ['Takeaway', 'Mobile order pickup', 'Free Wi-Fi'],
    hours: cafe,
    dining: {
      cuisines: ['Coffee', 'Bakery'],
      dietary: ['Vegetarian options', 'Plant-based milk'],
      dineIn: true,
      takeaway: true,
      delivery: true,
      priceBand: '₹₹',
      menuUrl: demoUrl('starbucks', 'menu'),
      reservationUrl: '',
    },
    hi: { shortSummary: 'हैंडक्राफ्टेड कॉफ़ी, कोल्ड ब्रू और बेकरी' },
  },
  {
    id: 'croma',
    name: 'Croma',
    categoryId: 'electronics',
    subcategory: 'Electronics superstore',
    floorId: 'l0',
    slot: 'T2',
    unitNumber: 'L0-03',
    brandColor: '#00a19a',
    shortSummary: 'TVs, laptops, mobile phones, appliances and gadgets.',
    description:
      'Compare TVs, laptops, mobile phones and kitchen appliances side by side, with demo zones and installation booking in store.',
    keywords: [
      'electronics',
      'tv',
      'television',
      'laptop',
      'mobile phone',
      'smartphone',
      'appliances',
      'headphones',
      'camera',
      'gaming',
    ],
    productTypes: ['Mobile phones', 'Laptops', 'Televisions', 'Appliances', 'Audio'],
    services: ['EMI options', 'Installation booking', 'Extended warranty'],
    brands: ['Samsung', 'Apple', 'Sony', 'LG', 'HP'],
  },
  {
    id: 'reliance-digital',
    name: 'Reliance Digital',
    categoryId: 'electronics',
    subcategory: 'Electronics & mobiles',
    floorId: 'l0',
    slot: 'T3',
    unitNumber: 'L0-04',
    brandColor: '#e42529',
    shortSummary: 'Mobiles, accessories, smart home and computing.',
    description:
      'Latest smartphones, accessories, smart-home devices and computing essentials, with a quick-service counter for SIM and setup help.',
    keywords: [
      'mobile phone',
      'phone',
      'smartphone',
      'accessories',
      'chargers',
      'smart home',
      'tablet',
      'computer',
      'electronics',
    ],
    productTypes: ['Smartphones', 'Accessories', 'Smart home', 'Tablets'],
    services: ['Phone setup help', 'Screen guard fitting', 'Exchange offers'],
  },
  {
    id: 'apollo-pharmacy',
    name: 'Apollo Pharmacy',
    categoryId: 'health',
    subcategory: 'Pharmacy',
    floorId: 'l0',
    slot: 'T4',
    unitNumber: 'L0-05',
    brandColor: '#0a7bc2',
    shortSummary: 'Prescriptions, wellness and personal care.',
    description:
      'Prescription and over-the-counter medicines, first-aid supplies, baby care and personal wellness products.',
    keywords: [
      'pharmacy',
      'chemist',
      'medicine',
      'medical',
      'first aid',
      'health',
      'baby care',
      'vitamins',
    ],
    productTypes: ['Medicines', 'Wellness', 'Baby care', 'Personal care'],
    services: ['Prescription dispensing', 'Blood-pressure check'],
    hours: dailyHours('09:00', '22:30'),
  },
  {
    id: 'superdry',
    name: 'Superdry',
    categoryId: 'fashion',
    subcategory: 'Casual wear',
    floorId: 'l0',
    slot: 'T5',
    unitNumber: 'L0-06',
    brandColor: '#f26b21',
    shortSummary: 'Jackets, hoodies and casual streetwear.',
    description:
      'Graphic tees, hoodies, jackets and weekend denim with a vintage-inspired, street-casual look.',
    keywords: ['jackets', 'hoodies', 'streetwear', 't-shirts', 'casual', 'men', 'women', 'clothes'],
    productTypes: ['Jackets', 'Hoodies', 'T-shirts', 'Denim'],
    services: ['Gift cards'],
  },
  {
    id: 'decathlon',
    name: 'Decathlon',
    categoryId: 'sports',
    subcategory: 'Sports superstore',
    floorId: 'l0',
    slot: 'TR',
    unitNumber: 'L0-07',
    anchor: true,
    brandColor: '#0082c3',
    shortSummary: 'Gear for 60+ sports — running, cycling, swimming and more.',
    description:
      'Try-before-you-buy sports equipment for running, cycling, swimming, racquet sports, yoga and camping, plus a bike workshop.',
    keywords: [
      'sports',
      'running shoes',
      'shoes',
      'cycling',
      'bicycle',
      'swimming',
      'yoga',
      'fitness',
      'gym',
      'camping',
      'badminton',
      'cricket',
    ],
    productTypes: ['Running shoes', 'Cycles', 'Fitness', 'Swimwear', 'Camping'],
    services: ['Cycle workshop', 'Racquet stringing', 'Try zone'],
  },
  {
    id: 'miniso',
    name: 'Miniso',
    categoryId: 'home',
    subcategory: 'Lifestyle & gifts',
    floorId: 'l0',
    slot: 'R1_SHORT',
    unitNumber: 'L0-08',
    brandColor: '#e60012',
    shortSummary: 'Playful gifts, stationery, beauty and home bits.',
    description:
      'Affordable, design-led gifts, plush toys, stationery, travel accessories and beauty minis.',
    keywords: ['gifts', 'stationery', 'toys', 'plush', 'accessories', 'home', 'cute', 'travel'],
    productTypes: ['Gifts', 'Stationery', 'Plush toys', 'Travel accessories'],
    services: ['Gift wrapping'],
  },
  {
    id: 'health-glow',
    name: 'Health & Glow',
    categoryId: 'beauty',
    subcategory: 'Beauty & personal care',
    floorId: 'l0',
    slot: 'R2_SHORT',
    unitNumber: 'L0-09',
    brandColor: '#8e2c7f',
    shortSummary: 'Makeup, skincare, haircare and wellness.',
    description:
      'Everyday makeup, skincare and haircare brands with testers and friendly beauty advisers.',
    keywords: [
      'makeup',
      'lipstick',
      'skincare',
      'haircare',
      'cosmetics',
      'fragrance',
      'nail polish',
      'beauty',
    ],
    productTypes: ['Makeup', 'Skincare', 'Haircare', 'Fragrance'],
    services: ['Skin analysis', 'Beauty advice'],
  },
  {
    id: 'freshmart',
    name: 'FreshMart Express',
    categoryId: 'grocery',
    subcategory: 'Convenience store',
    floorId: 'l0',
    slot: 'B1',
    unitNumber: 'L0-10',
    brandColor: '#3aa655',
    shortSummary: 'Snacks, drinks, groceries and daily essentials.',
    description:
      'Grab-and-go snacks, chilled drinks, fresh fruit and daily essentials — ideal before you head home.',
    keywords: [
      'grocery',
      'groceries',
      'supermarket',
      'convenience',
      'snacks',
      'drinks',
      'water',
      'essentials',
      'fruit',
    ],
    productTypes: ['Snacks', 'Drinks', 'Fresh produce', 'Household'],
    services: ['Self checkout', 'Bill payments'],
    hours: dailyHours('09:00', '22:30'),
  },
  {
    id: 'mcdonalds',
    name: "McDonald's",
    categoryId: 'dining',
    subcategory: 'Quick service',
    floorId: 'l0',
    slot: 'L1_SHORT',
    unitNumber: 'L0-11',
    brandColor: '#da291c',
    shortSummary: 'Burgers, fries, wraps and McCafé.',
    description:
      'Burgers, wraps, fries and shakes with a McCafé counter and self-order kiosks near the parking lobby.',
    keywords: ['burger', 'fries', 'fast food', 'quick bite', 'kids meal', 'shake', 'cheap eats'],
    productTypes: ['Burgers', 'Wraps', 'Fries', 'Desserts'],
    services: ['Self-order kiosk', 'Takeaway', 'Birthday parties'],
    hours: dining,
    dining: {
      cuisines: ['Burgers', 'Fast food'],
      dietary: ['Vegetarian options'],
      dineIn: true,
      takeaway: true,
      delivery: true,
      priceBand: '₹',
      menuUrl: demoUrl('mcdonalds', 'menu'),
      reservationUrl: '',
    },
  },
  {
    id: 'samsung-service',
    name: 'Samsung Service Centre',
    categoryId: 'services',
    subcategory: 'Device repair',
    floorId: 'l0',
    slot: 'L2_SHORT',
    unitNumber: 'L0-12',
    brandColor: '#1428a0',
    shortSummary: 'Phone and tablet repairs, battery and screen service.',
    description:
      'Authorised walk-in repairs for phones, tablets and wearables, including screen and battery replacement.',
    keywords: [
      'repair',
      'phone repair',
      'screen replacement',
      'battery',
      'service centre',
      'warranty',
      'mobile phone',
    ],
    productTypes: ['Screen repair', 'Battery replacement', 'Software support'],
    services: ['Walk-in repairs', 'Warranty claims', 'Pickup when ready'],
    hours: dailyHours('10:00', '20:00'),
  },

  /* ---------------------------- L1 · Fashion & Lifestyle ---------------------------- */
  {
    id: 'zara',
    name: 'Zara',
    categoryId: 'fashion',
    subcategory: 'Fashion',
    floorId: 'l1',
    slot: 'TL',
    unitNumber: 'L1-01',
    anchor: true,
    brandColor: '#111111',
    heroImage: '/demo/stores/zara.webp',
    shortSummary: 'Contemporary fashion for women, men and kids.',
    description:
      'Runway-inspired collections for women, men and kids, with new styles arriving every week.',
    keywords: [
      'fashion',
      'clothes',
      'dresses',
      'jackets',
      'women',
      'men',
      'kids clothes',
      'shoes',
      'bags',
    ],
    productTypes: ['Womenswear', 'Menswear', 'Kids', 'Shoes & bags'],
    services: ['Online order pickup', 'Returns'],
  },
  {
    id: 'hm',
    name: 'H&M',
    categoryId: 'fashion',
    subcategory: 'Fashion',
    floorId: 'l1',
    slot: 'T1',
    unitNumber: 'L1-02',
    brandColor: '#e50010',
    shortSummary: 'Fashion basics and trends for the whole family.',
    description:
      'Wardrobe essentials, trend pieces and a kids department, plus a garment-recycling drop-off.',
    keywords: ['fashion', 'basics', 'kids clothes', 'women', 'men', 'clothes', 'affordable'],
    productTypes: ['Womenswear', 'Menswear', 'Kids', 'Accessories'],
    services: ['Garment recycling', 'Online returns'],
  },
  {
    id: 'uniqlo',
    name: 'Uniqlo',
    categoryId: 'fashion',
    subcategory: 'Everyday essentials',
    floorId: 'l1',
    slot: 'T2',
    unitNumber: 'L1-03',
    brandColor: '#ff0000',
    shortSummary: 'LifeWear essentials — tees, knitwear and outerwear.',
    description:
      'Simple, high-quality everyday clothing: supima tees, merino knitwear, light down jackets and UT graphic tees.',
    keywords: ['basics', 't-shirts', 'knitwear', 'jackets', 'innerwear', 'clothes', 'kids clothes'],
    productTypes: ['T-shirts', 'Knitwear', 'Outerwear', 'Innerwear'],
    services: ['Free hemming', 'Online order pickup'],
  },
  {
    id: 'sephora',
    name: 'Sephora',
    categoryId: 'beauty',
    subcategory: 'Beauty & fragrance',
    floorId: 'l1',
    slot: 'T3',
    unitNumber: 'L1-04',
    brandColor: '#000000',
    shortSummary: 'Makeup, skincare and fragrance from global brands.',
    description:
      'Discover makeup, skincare, haircare and fragrance, with try-on bars and complimentary mini makeovers.',
    keywords: [
      'makeup',
      'lipstick',
      'foundation',
      'skincare',
      'perfume',
      'fragrance',
      'cosmetics',
      'beauty',
    ],
    productTypes: ['Makeup', 'Skincare', 'Fragrance', 'Haircare'],
    services: ['Mini makeovers', 'Skin consultation', 'Gift wrapping'],
    hi: { shortSummary: 'मेकअप, स्किनकेयर और खुशबू' },
  },
  {
    id: 'nike',
    name: 'Nike',
    categoryId: 'fashion',
    subcategory: 'Sportswear & footwear',
    floorId: 'l1',
    slot: 'T4',
    unitNumber: 'L1-05',
    brandColor: '#111111',
    shortSummary: 'Running shoes, sneakers and performance sportswear.',
    description:
      'Running shoes, lifestyle sneakers and training apparel, with a treadmill gait check to find your fit.',
    keywords: [
      'shoes',
      'running shoes',
      'sneakers',
      'trainers',
      'sportswear',
      'gym',
      'football',
      'basketball',
    ],
    productTypes: ['Running shoes', 'Sneakers', 'Training apparel', 'Accessories'],
    services: ['Gait analysis', 'Member rewards'],
  },
  {
    id: 'adidas',
    name: 'Adidas',
    categoryId: 'fashion',
    subcategory: 'Sportswear & footwear',
    floorId: 'l1',
    slot: 'T5',
    unitNumber: 'L1-06',
    brandColor: '#000000',
    shortSummary: 'Originals sneakers, running and football gear.',
    description:
      'Originals classics, running shoes, football boots and training wear for every sport.',
    keywords: [
      'shoes',
      'running shoes',
      'sneakers',
      'trainers',
      'sportswear',
      'football',
      'tracksuit',
    ],
    productTypes: ['Sneakers', 'Running shoes', 'Football', 'Tracksuits'],
    services: ['Member rewards', 'Online order pickup'],
  },
  {
    id: 'apple',
    name: 'Apple',
    categoryId: 'electronics',
    subcategory: 'Premium tech',
    floorId: 'l1',
    slot: 'TR',
    unitNumber: 'L1-07',
    anchor: true,
    brandColor: '#1d1d1f',
    shortSummary: 'iPhone, Mac, iPad, Watch and expert help.',
    description:
      'Explore iPhone, Mac, iPad and Apple Watch hands-on, with free setup sessions and a support bar for repairs.',
    keywords: [
      'iphone',
      'mobile phone',
      'phone',
      'smartphone',
      'mac',
      'laptop',
      'ipad',
      'tablet',
      'watch',
      'airpods',
      'electronics',
    ],
    productTypes: ['iPhone', 'Mac', 'iPad', 'Watch', 'Accessories'],
    services: ['Setup sessions', 'Repairs & support', 'Trade-in'],
  },
  {
    id: 'lifestyle',
    name: 'Lifestyle',
    categoryId: 'fashion',
    subcategory: 'Department store',
    floorId: 'l1',
    slot: 'R1',
    unitNumber: 'L1-08',
    brandColor: '#f7a600',
    shortSummary: 'Fashion, footwear, beauty and kids under one roof.',
    description:
      'A multi-brand fashion department store with ethnic and western wear, footwear, handbags, beauty and kids.',
    keywords: [
      'department store',
      'ethnic wear',
      'kurta',
      'western wear',
      'shoes',
      'handbags',
      'kids clothes',
      'clothes',
    ],
    productTypes: ['Ethnic wear', 'Western wear', 'Footwear', 'Kids'],
    services: ['Alterations', 'Loyalty points'],
  },
  {
    id: 'levis',
    name: "Levi's",
    categoryId: 'fashion',
    subcategory: 'Denim',
    floorId: 'l1',
    slot: 'R2',
    unitNumber: 'L1-09',
    brandColor: '#c41230',
    shortSummary: 'Iconic jeans, jackets and denim tailoring.',
    description:
      'The 501 and every fit in between, trucker jackets and a tailor shop for hemming and customisation.',
    keywords: ['jeans', 'denim', 'jackets', 'clothes', 'men', 'women'],
    productTypes: ['Jeans', 'Denim jackets', 'Tops'],
    services: ['Hemming & tailoring', 'Customisation'],
  },
  {
    id: 'body-shop',
    name: 'The Body Shop',
    categoryId: 'beauty',
    subcategory: 'Natural beauty',
    floorId: 'l1',
    slot: 'B5',
    unitNumber: 'L1-10',
    brandColor: '#004236',
    shortSummary: 'Vegan skincare, body butters and gifts.',
    description:
      'Ethically sourced skincare, body care and fragrance — with a refill station for your empty bottles.',
    keywords: ['skincare', 'body butter', 'vegan', 'gifts', 'fragrance', 'beauty', 'makeup'],
    productTypes: ['Skincare', 'Body care', 'Hair care', 'Gift sets'],
    services: ['Refill station', 'Gift wrapping'],
  },
  {
    id: 'westside',
    name: 'Westside',
    categoryId: 'fashion',
    subcategory: 'Fashion & home',
    floorId: 'l1',
    slot: 'B3_B4',
    unitNumber: 'L1-11',
    anchor: true,
    brandColor: '#2b2b2b',
    shortSummary: 'Everyday fashion, ethnic wear and home décor.',
    description:
      'Great-value fashion for the family with ethnic and western collections, plus a home section of décor and linen.',
    keywords: ['fashion', 'ethnic wear', 'kids clothes', 'clothes', 'home decor', 'women', 'men'],
    productTypes: ['Womenswear', 'Menswear', 'Kidswear', 'Home'],
    services: ['Alterations', 'Club rewards'],
  },
  {
    id: 'samsung',
    name: 'Samsung Experience Store',
    categoryId: 'electronics',
    subcategory: 'Mobiles & wearables',
    floorId: 'l1',
    slot: 'B2',
    unitNumber: 'L1-12',
    brandColor: '#1428a0',
    shortSummary: 'Galaxy phones, tablets, watches and smart TVs.',
    description:
      'Try the latest Galaxy phones, foldables, watches and tablets, with trade-in and Samsung Care+ options.',
    keywords: [
      'mobile phone',
      'phone',
      'smartphone',
      'galaxy',
      'tablet',
      'watch',
      'tv',
      'electronics',
    ],
    productTypes: ['Galaxy phones', 'Tablets', 'Wearables', 'Smart TVs'],
    services: ['Trade-in', 'Care+ protection'],
  },
  {
    id: 'home-centre',
    name: 'Home Centre',
    categoryId: 'home',
    subcategory: 'Furniture & décor',
    floorId: 'l1',
    slot: 'B1',
    unitNumber: 'L1-13',
    brandColor: '#8a5a44',
    shortSummary: 'Furniture, décor, bedding and kitchenware.',
    description: 'Sofas, dining sets, bedding, lighting and kitchenware to refresh every room.',
    keywords: ['furniture', 'home decor', 'bedding', 'kitchen', 'lamps', 'cushions', 'home'],
    productTypes: ['Furniture', 'Décor', 'Bedding', 'Kitchenware'],
    services: ['Home delivery', 'Design consultation'],
  },
  {
    id: 'little-explorers',
    name: 'Little Explorers',
    categoryId: 'kids',
    subcategory: 'Kids clothing & toys',
    floorId: 'l1',
    slot: 'L2',
    unitNumber: 'L1-14',
    brandColor: '#ff8a3d',
    shortSummary: 'Kids clothes, school shoes and learning toys.',
    description:
      'Playful clothing for ages 0–12, school shoes and a hand-picked toy wall of STEM kits and puzzles.',
    keywords: [
      'kids clothes',
      'children',
      'baby clothes',
      'toys',
      'school shoes',
      'kids',
      'puzzles',
    ],
    productTypes: ['Kidswear', 'Baby', 'Toys', 'School shoes'],
    services: ['Gift wrapping', 'Birthday registry'],
  },
  {
    id: 'sunglass-hut',
    name: 'Sunglass Hut',
    categoryId: 'fashion',
    subcategory: 'Eyewear',
    floorId: 'l1',
    slot: 'L1',
    unitNumber: 'L1-15',
    brandColor: '#231f20',
    shortSummary: 'Designer sunglasses and sports eyewear.',
    description:
      'Designer and sports sunglasses with polarised lenses, fitting adjustments and cleaning.',
    keywords: ['sunglasses', 'eyewear', 'shades', 'accessories', 'glasses'],
    productTypes: ['Sunglasses', 'Sports eyewear'],
    services: ['Frame adjustment', 'Lens cleaning'],
    brands: ['Ray-Ban', 'Oakley', 'Prada'],
  },

  /* ---------------------------- L2 · Cinema & Dining ---------------------------- */
  {
    id: 'pvr',
    name: 'PVR Cinemas',
    categoryId: 'cinema',
    subcategory: 'Multiplex cinema',
    floorId: 'l2',
    slot: 'CINEMA',
    unitNumber: 'L2-01',
    anchor: true,
    brandColor: '#e5b700',
    shortSummary: '8-screen multiplex with recliner and IMAX-style screens.',
    description:
      'Eight screens including recliner lounges and a large-format screen, gourmet popcorn and a café bar in the lobby.',
    keywords: [
      'cinema',
      'movies',
      'movie',
      'films',
      'imax',
      'popcorn',
      'theatre',
      'showtimes',
      'tickets',
    ],
    productTypes: ['Movies', 'Recliner seats', 'Large format', 'Snacks'],
    services: ['Online booking', 'Wheelchair seating', 'Birthday screenings'],
    hours: dailyHours('09:30', '01:00'),
    accessibilityNotes: 'Wheelchair spaces in every auditorium; lift access directly to the lobby.',
    cinema: {
      screens: 8,
      bookingUrl: demoUrl('pvr', 'tickets'),
      showtimes: [
        {
          id: 'st-1',
          title: 'The Last Horizon',
          rating: 'UA13+',
          language: 'English',
          durationMinutes: 142,
          times: ['11:20', '14:45', '18:10', '21:30'],
        },
        {
          id: 'st-2',
          title: 'Monsoon Diaries',
          rating: 'U',
          language: 'Hindi',
          durationMinutes: 128,
          times: ['10:40', '13:50', '17:05', '20:25'],
        },
        {
          id: 'st-3',
          title: 'Rocket Pup 2',
          rating: 'U',
          language: 'English',
          durationMinutes: 96,
          times: ['10:15', '12:30', '15:00'],
        },
        {
          id: 'st-4',
          title: 'Namma Ooru',
          rating: 'UA7+',
          language: 'Kannada',
          durationMinutes: 151,
          times: ['12:10', '16:00', '19:45'],
        },
      ],
    },
  },
  {
    id: 'pizza-express',
    name: 'Pizza Express',
    categoryId: 'dining',
    subcategory: 'Italian restaurant',
    floorId: 'l2',
    slot: 'T2',
    unitNumber: 'L2-02',
    brandColor: '#1a3c5a',
    shortSummary: 'Italian pizzeria — Romana pizzas, pasta and dough balls.',
    description:
      'Italian-style thin-crust Romana pizzas, baked pasta, dough balls and gelato in a relaxed, family-friendly dining room.',
    keywords: [
      'italian',
      'italian food',
      'pizza',
      'pasta',
      'family dining',
      'dough balls',
      'restaurant',
      'dinner',
    ],
    productTypes: ['Pizza', 'Pasta', 'Salads', 'Desserts'],
    services: ['Dine-in', 'Takeaway', 'Kids menu'],
    hours: dining,
    dining: {
      cuisines: ['Italian', 'Pizza'],
      dietary: ['Vegetarian options', 'Gluten-free base'],
      dineIn: true,
      takeaway: true,
      delivery: true,
      priceBand: '₹₹₹',
      menuUrl: demoUrl('pizza-express', 'menu'),
      reservationUrl: demoUrl('pizza-express', 'book'),
    },
  },
  {
    id: 'barbeque-nation',
    name: 'Barbeque Nation',
    categoryId: 'dining',
    subcategory: 'Casual dining',
    floorId: 'l2',
    slot: 'T3',
    unitNumber: 'L2-03',
    brandColor: '#c8102e',
    shortSummary: 'Live grill-on-the-table buffet.',
    description:
      'Unlimited live-grill starters cooked at your table, followed by a generous buffet of mains and desserts.',
    keywords: [
      'barbeque',
      'bbq',
      'grill',
      'buffet',
      'north indian',
      'family dining',
      'restaurant',
      'kebab',
    ],
    productTypes: ['Live grill', 'Buffet', 'Kebabs', 'Desserts'],
    services: ['Table booking', 'Group celebrations'],
    hours: dining,
    dining: {
      cuisines: ['North Indian', 'Barbeque'],
      dietary: ['Vegetarian', 'Non-vegetarian', 'Jain options'],
      dineIn: true,
      takeaway: false,
      delivery: false,
      priceBand: '₹₹₹',
      menuUrl: demoUrl('barbeque-nation', 'menu'),
      reservationUrl: demoUrl('barbeque-nation', 'book'),
    },
  },
  {
    id: 'coffee-bean',
    name: 'The Coffee Bean & Tea Leaf',
    categoryId: 'dining',
    subcategory: 'Café',
    floorId: 'l2',
    slot: 'T4',
    unitNumber: 'L2-04',
    brandColor: '#4b2e83',
    shortSummary: 'Ice blended drinks, coffee and tea.',
    description:
      'Signature ice blended drinks, single-origin coffee, loose-leaf teas and light bites with views over the atrium.',
    keywords: ['coffee', 'cafe', 'tea', 'ice blended', 'latte', 'dessert', 'wifi'],
    productTypes: ['Coffee', 'Tea', 'Ice blended', 'Light bites'],
    services: ['Free Wi-Fi', 'Takeaway'],
    hours: cafe,
    dining: {
      cuisines: ['Coffee', 'Tea'],
      dietary: ['Vegetarian options'],
      dineIn: true,
      takeaway: true,
      delivery: false,
      priceBand: '₹₹',
      menuUrl: demoUrl('coffee-bean', 'menu'),
      reservationUrl: '',
    },
  },
  {
    id: 'keventers',
    name: 'Keventers',
    categoryId: 'dining',
    subcategory: 'Shakes & desserts',
    floorId: 'l2',
    slot: 'T5',
    unitNumber: 'L2-05',
    brandColor: '#d7263d',
    shortSummary: 'Thick milkshakes served in glass bottles.',
    description:
      'Classic thick milkshakes, sundaes and hot dogs served in the brand’s signature glass bottles.',
    keywords: ['milkshake', 'shake', 'dessert', 'ice cream', 'sweet', 'drinks'],
    productTypes: ['Milkshakes', 'Sundaes', 'Hot dogs'],
    services: ['Takeaway'],
    hours: dining,
    dining: {
      cuisines: ['Desserts', 'Beverages'],
      dietary: ['Vegetarian'],
      dineIn: false,
      takeaway: true,
      delivery: true,
      priceBand: '₹',
      menuUrl: demoUrl('keventers', 'menu'),
      reservationUrl: '',
    },
  },
  {
    id: 'mainland-china',
    name: 'Mainland China',
    categoryId: 'dining',
    subcategory: 'Chinese restaurant',
    floorId: 'l2',
    slot: 'TR',
    unitNumber: 'L2-06',
    anchor: true,
    brandColor: '#a4161a',
    shortSummary: 'Cantonese, Sichuan and dim sum.',
    description:
      'Dim sum, Sichuan specialities and Cantonese classics served family-style in an elegant dining room.',
    keywords: ['chinese', 'dim sum', 'noodles', 'sichuan', 'asian', 'restaurant', 'dinner'],
    productTypes: ['Dim sum', 'Noodles', 'Sichuan', 'Seafood'],
    services: ['Table booking', 'Private dining'],
    hours: dining,
    dining: {
      cuisines: ['Chinese', 'Asian'],
      dietary: ['Vegetarian options', 'Non-vegetarian'],
      dineIn: true,
      takeaway: true,
      delivery: true,
      priceBand: '₹₹₹',
      menuUrl: demoUrl('mainland-china', 'menu'),
      reservationUrl: demoUrl('mainland-china', 'book'),
    },
  },
  {
    id: 'olive-trattoria',
    name: 'Olive Trattoria',
    categoryId: 'dining',
    subcategory: 'Italian restaurant',
    floorId: 'l2',
    slot: 'R1',
    unitNumber: 'L2-07',
    brandColor: '#556b2f',
    shortSummary: 'Handmade pasta, wood-fired pizza and Italian classics.',
    description:
      'A warm neighbourhood trattoria serving handmade pasta, wood-fired Neapolitan pizza, risotto and tiramisu — with vegetarian and Jain-friendly options.',
    keywords: [
      'italian',
      'italian food',
      'pasta',
      'pizza',
      'risotto',
      'tiramisu',
      'family dining',
      'restaurant',
      'date night',
      'wine',
    ],
    productTypes: ['Handmade pasta', 'Wood-fired pizza', 'Risotto', 'Desserts'],
    services: ['Dine-in', 'Takeaway', 'Table booking'],
    hours: dining,
    accessibilityNotes:
      'Step-free entrance from the Level 2 corridor; accessible table near the entrance.',
    dining: {
      cuisines: ['Italian', 'Pizza', 'Pasta'],
      dietary: ['Vegetarian options', 'Jain options', 'Gluten-free pasta'],
      dineIn: true,
      takeaway: true,
      delivery: false,
      priceBand: '₹₹₹',
      menuUrl: demoUrl('olive-trattoria', 'menu'),
      reservationUrl: demoUrl('olive-trattoria', 'book'),
    },
    hi: { shortSummary: 'हाथ से बना पास्ता, वुड-फायर्ड पिज़्ज़ा और इटैलियन व्यंजन' },
  },
  {
    id: 'burger-king',
    name: 'Burger King',
    categoryId: 'dining',
    subcategory: 'Quick service',
    floorId: 'l2',
    slot: 'R2',
    unitNumber: 'L2-08',
    brandColor: '#d62300',
    shortSummary: 'Flame-grilled Whoppers, fries and shakes.',
    description: 'Flame-grilled burgers, crispy fries and shakes — quick, filling and great value.',
    keywords: ['burger', 'fast food', 'fries', 'quick bite', 'whopper', 'cheap eats'],
    productTypes: ['Burgers', 'Fries', 'Shakes'],
    services: ['Takeaway', 'Self-order kiosk'],
    hours: dining,
    dining: {
      cuisines: ['Burgers', 'Fast food'],
      dietary: ['Vegetarian options'],
      dineIn: true,
      takeaway: true,
      delivery: true,
      priceBand: '₹',
      menuUrl: demoUrl('burger-king', 'menu'),
      reservationUrl: '',
    },
  },
  {
    id: 'haldirams',
    name: "Haldiram's",
    categoryId: 'dining',
    subcategory: 'Indian vegetarian',
    floorId: 'l2',
    slot: 'B5',
    unitNumber: 'L2-09',
    brandColor: '#e30613',
    shortSummary: 'Vegetarian thalis, chaat and Indian sweets.',
    description:
      'Pure-vegetarian thalis, South Indian favourites, chaat and a sweets counter for gifting.',
    keywords: [
      'indian',
      'vegetarian',
      'thali',
      'chaat',
      'sweets',
      'mithai',
      'south indian',
      'dosa',
      'snacks',
    ],
    productTypes: ['Thali', 'Chaat', 'South Indian', 'Sweets'],
    services: ['Takeaway', 'Sweet boxes'],
    hours: dining,
    dining: {
      cuisines: ['North Indian', 'South Indian', 'Sweets'],
      dietary: ['Pure vegetarian', 'Jain options'],
      dineIn: true,
      takeaway: true,
      delivery: true,
      priceBand: '₹₹',
      menuUrl: demoUrl('haldirams', 'menu'),
      reservationUrl: '',
    },
  },
  {
    id: 'food-court',
    name: 'Riverside Food Court',
    categoryId: 'dining',
    subcategory: 'Food court',
    floorId: 'l2',
    slot: 'B3_B4',
    unitNumber: 'L2-10',
    anchor: true,
    brandColor: '#f28c28',
    shortSummary: '12 counters — biryani, dosa, momos, wraps and more.',
    description:
      'Twelve quick-service counters around shared seating: biryani, dosa, momos, Korean bowls, wraps, juices and more.',
    keywords: [
      'food court',
      'food',
      'quick bite',
      'biryani',
      'dosa',
      'momos',
      'wraps',
      'juice',
      'lunch',
    ],
    productTypes: ['Biryani', 'South Indian', 'Momos', 'Wraps', 'Juices'],
    services: ['Shared seating', 'Baby chairs', 'Handwash area'],
    hours: dailyHours('11:00', '22:30'),
    accessibilityNotes:
      'Step-free seating area with accessible tables and nearby accessible washrooms.',
    dining: {
      cuisines: ['Multi-cuisine', 'Indian', 'Asian'],
      dietary: ['Vegetarian options', 'Non-vegetarian', 'Jain options'],
      dineIn: true,
      takeaway: true,
      delivery: false,
      priceBand: '₹',
      menuUrl: '',
      reservationUrl: '',
    },
  },
  {
    id: 'gelato-room',
    name: 'Gelato Room',
    categoryId: 'dining',
    subcategory: 'Dessert parlour',
    floorId: 'l2',
    slot: 'B2',
    unitNumber: 'L2-11',
    brandColor: '#e75480',
    shortSummary: 'Small-batch gelato, sorbets and waffles.',
    description:
      'Twenty-four flavours of small-batch gelato and sorbet made daily, plus waffles and affogato.',
    keywords: ['dessert', 'gelato', 'ice cream', 'sorbet', 'waffles', 'sweet', 'italian'],
    productTypes: ['Gelato', 'Sorbet', 'Waffles', 'Affogato'],
    services: ['Takeaway tubs', 'Tasting spoons'],
    hours: dailyHours('11:30', '23:00'),
    dining: {
      cuisines: ['Desserts'],
      dietary: ['Vegan sorbets', 'Eggless'],
      dineIn: true,
      takeaway: true,
      delivery: false,
      priceBand: '₹₹',
      menuUrl: demoUrl('gelato-room', 'menu'),
      reservationUrl: '',
    },
  },
  {
    id: 'funcity',
    name: 'FunCity Play Zone',
    categoryId: 'kids',
    subcategory: 'Kids play area',
    floorId: 'l2',
    slot: 'B1',
    unitNumber: 'L2-12',
    brandColor: '#7c3aed',
    shortSummary: 'Soft play, trampolines and party rooms for kids.',
    description:
      'Supervised soft play, mini trampolines and creative corners for ages 2–10, with bookable birthday rooms.',
    keywords: [
      'kids',
      'children',
      'play area',
      'soft play',
      'birthday party',
      'family',
      'toddlers',
    ],
    productTypes: ['Soft play', 'Trampolines', 'Party rooms'],
    services: ['Birthday parties', 'Supervised play'],
    hours: dailyHours('11:00', '21:30'),
  },
  {
    id: 'timezone',
    name: 'Timezone',
    categoryId: 'entertainment',
    subcategory: 'Arcade & bowling',
    floorId: 'l2',
    slot: 'L2',
    unitNumber: 'L2-13',
    brandColor: '#0055ff',
    shortSummary: 'Arcade games, bowling and VR experiences.',
    description:
      'Arcade classics, racing simulators, VR experiences and a four-lane bowling alley for friends and family.',
    keywords: ['games', 'arcade', 'bowling', 'vr', 'gaming', 'entertainment', 'fun', 'family'],
    productTypes: ['Arcade', 'Bowling', 'VR', 'Prizes'],
    services: ['Party packages', 'Power cards'],
    hours: dailyHours('11:00', '23:00'),
  },
];
