/**
 * Draft transcription of the ground-floor plan supplied on 2026-09-23.
 * Coordinates refer to the supplied 1269 × 891 image, NOT metres.
 * Label points identify approximate units; they are not entrance/route nodes.
 * Keep separate from published content until door positions and kiosk are confirmed.
 */
export const groundFloorSurvey = {
  status: 'draft',
  sourceSize: { width: 1269, height: 891 },
  kiosk: null,
  metresPerPixel: null,
  brands: [
    { name: 'Ensemble', point: [62, 225] },
    { name: 'OTT', point: [64, 345] },
    { name: 'Cafe Dori', point: [144, 174] },
    { name: 'Nappa Dori', point: [201, 174] },
    { name: 'Shantanu and Nikhil', point: [282, 174] },
    { name: 'Masaba', point: [339, 174] },
    { name: 'JJ Valaya', point: [144, 333] },
    { name: 'JJ Valaya', point: [202, 333] },
    { name: 'Nappa Dori', point: [291, 257], needsReview: true },
    { name: 'Sundays', point: [356, 275] },
    { name: 'Nykaa Luxe', point: [282, 344] },
    { name: 'Nykaa Luxe', point: [335, 344] },
    { name: 'Suvasa', point: [484, 175] },
    { name: 'Suvasa', point: [541, 175] },
    { name: 'Forest Essentials', point: [540, 257] },
    { name: 'Da Milano', point: [465, 330] },
    { name: 'Pure Home and Living', point: [539, 337] },
    { name: 'Love Birds', point: [620, 175] },
    { name: 'Love Birds', point: [679, 175] },
    { name: 'Good Earth', point: [620, 332] },
    { name: 'Good Earth', point: [679, 332] },
    { name: 'Starbucks', point: [759, 191] },
    { name: 'Parisian', point: [759, 284] },
    { name: 'Soulfoods', point: [174, 663] },
    { name: 'Veg Non Veg', point: [351, 550] },
    { name: 'Perona', point: [341, 693] },
    { name: 'Kama Ayurveda', point: [467, 500] },
    { name: 'Pinklay', point: [541, 500] },
    { name: 'RUH', point: [468, 566] },
    { name: 'Fat Lulus', point: [541, 578] },
    { name: 'Spin', point: [483, 688] },
    { name: 'Good Earth', point: [620, 503] },
    { name: 'Good Earth', point: [679, 503] },
    { name: 'Eka', point: [620, 714] },
    { name: 'Eka', point: [678, 714] },
    { name: 'Nicobar', point: [759, 530] },
    { name: 'Sober Decor', point: [759, 640] },
    { name: 'Hatsu', point: [759, 681] },
    { name: 'Coyu', point: [896, 657] },
  ],
  notes: [
    'Repeated names may occupy adjoining units; keep the geometry separate until confirmed.',
    'Several green retail blocks have no brand callout; retain as unassigned units.',
    'Hatched upper-right footprint is unassigned; do not invent retail destinations there.',
    'Lift and stair cores are visible, but accessibility and public entry points need confirmation.',
    'Corridor centre lines, shop entrances and measured scale must be confirmed before routing.',
  ],
} as const;
