type Store = {
  id: string;
  name: string;
  x: number;
  y: number;
  category: string;
  color: string;
  left?: boolean;
  floorId: string;
};
const positions: [number, number, boolean?][] = [
  [190, 108],
  [330, 100],
  [475, 77],
  [610, 148],
  [305, 205],
  [435, 225],
  [210, 269],
  [610, 345],
  [758, 290],
  [772, 364],
  [760, 438],
  [590, 440],
  [574, 515],
  [738, 553],
  [740, 634],
  [605, 606],
  [606, 700],
  [680, 751],
  [535, 790],
  [592, 843],
  [453, 854],
  [475, 917],
  [225, 125],
  [275, 185],
  [390, 88],
  [525, 125],
  [545, 205],
  [665, 255],
  [690, 315],
  [700, 385],
  [680, 455],
  [655, 525],
  [700, 590],
  [655, 665],
  [635, 720],
  [565, 755],
  [505, 815],
  [430, 895],
  [530, 880],
  [615, 790],
];
const first = [
  ['Apple', 'electronics'],
  ['Pandora', 'services'],
  ['Croma', 'electronics'],
  ['Gap', 'fashion'],
  ['LensCrafters', 'services'],
  ['Skechers', 'fashion'],
  ['Only', 'fashion'],
  ['Superdry', 'fashion'],
  ['KFC', 'dining'],
  ['Theobroma', 'dining'],
  ['Biba', 'fashion'],
  ['Diesel', 'fashion'],
  ['Fabindia', 'services'],
  ['Costa Coffee', 'dining'],
  ['U.S. Polo Assn.', 'fashion'],
  ['JBL', 'electronics'],
  ['Westside', 'fashion'],
  ['Bata', 'fashion'],
  ['Nykaa', 'beauty'],
  ["Dunkin'", 'dining'],
  ['Asics', 'fashion'],
  ['Pepperfry', 'services'],
  ['Zudio', 'fashion'],
  ['The Body Shop', 'beauty'],
  ['Jack & Jones', 'fashion'],
  ['Imagine', 'electronics'],
  ['Aurelia', 'fashion'],
  ['Pizza Hut', 'dining'],
  ['Forest Essentials', 'beauty'],
  ['Van Heusen', 'fashion'],
  ['Colorbar', 'beauty'],
  ['Wow Momo', 'dining'],
  ['Allen Solly', 'fashion'],
  ['Hamleys', 'services'],
  ['Mochi', 'fashion'],
  ['Chai Point', 'dining'],
  ['Reliance Digital', 'electronics'],
  ['Mothercare', 'fashion'],
  ['Tanishq', 'services'],
  ['Home Stop', 'services'],
];
const second = [
  ['Mobile Snap', 'electronics'],
  ['Blue Ruby', 'services'],
  ['Microsoft', 'electronics'],
  ['American Eagle Outfitters', 'fashion'],
  ['Shefield & Sons', 'services'],
  ['One Tooth', 'services'],
  ['Mendocino', 'fashion'],
  ['Banana Republic', 'fashion'],
  ['New York Fries', 'dining'],
  ["Purdy's Chocolates", 'dining'],
  ['Cleo', 'fashion'],
  ['Michael Kors', 'fashion'],
  ['The Bombay Company', 'services'],
  ['Tim Hortons', 'dining'],
  ['Hugo Boss', 'fashion'],
  ['Telus', 'electronics'],
  ['Holt Renfrew', 'fashion'],
  ['Ardene', 'fashion'],
  ["Victoria's Secret", 'fashion'],
  ['Treats', 'dining'],
  ['Reebok', 'fashion'],
  ['Royal Doulton', 'services'],
  ['Roots', 'fashion'],
  ['Watch It!', 'services'],
  ['Urban Kids', 'fashion'],
  ['Momo', 'dining'],
  ['Pink', 'fashion'],
  ['Sbarro', 'dining'],
  ['Northern Reflections', 'fashion'],
  ['Scenic Rush', 'services'],
  ['Boathouse', 'fashion'],
  ['Naturalizer', 'fashion'],
  ['Q Nails', 'beauty'],
  ['Hugo Boss Kids', 'fashion'],
  ['Apple Store', 'electronics'],
  ['Lens Factory', 'services'],
  ['Bath & Body', 'beauty'],
  ['Foot Locker', 'fashion'],
  ['Peoples Jewellers', 'services'],
  ['Freshii', 'dining'],
];
const third = [
  ['Samsung', 'electronics'],
  ['Swarovski', 'services'],
  ['Sony', 'electronics'],
  ["Levi's", 'fashion'],
  ['Miniso', 'services'],
  ['Puma', 'fashion'],
  ['Mango', 'fashion'],
  ['Uniqlo', 'fashion'],
  ['Burger King', 'dining'],
  ['Lindt', 'dining'],
  ['Vero Moda', 'fashion'],
  ['Calvin Klein', 'fashion'],
  ['Muji', 'services'],
  ['Starbucks', 'dining'],
  ['Tommy Jeans', 'fashion'],
  ['Bose', 'electronics'],
  ['Marks & Spencer', 'fashion'],
  ['Crocs', 'fashion'],
  ['MAC Cosmetics', 'beauty'],
  ['Baskin Robbins', 'dining'],
  ['New Balance', 'fashion'],
  ['Home Centre', 'services'],
  ['Under Armour', 'fashion'],
  ['Titan Eye+', 'services'],
  ['OnePlus', 'electronics'],
  ['Forever New', 'fashion'],
  ['Health & Glow', 'beauty'],
  ['Taco Bell', 'dining'],
  ['Rare Rabbit', 'fashion'],
  ['Aldo', 'fashion'],
  ['Sephora Studio', 'beauty'],
  ['Third Wave Coffee', 'dining'],
  ['Celio', 'fashion'],
  ['Crossword', 'services'],
  ['Steve Madden', 'fashion'],
  ['Keventers', 'dining'],
  ['Vijay Sales', 'electronics'],
  ["Mother's Recipe", 'dining'],
  ['CaratLane', 'services'],
  ['Urban Ladder', 'services'],
];
const colors: Record<string, string> = {
  fashion: '#b55787',
  dining: '#ef741d',
  services: '#466d93',
  electronics: '#2672d6',
  beauty: '#18a4cc',
};
export const upperStores: Store[] = [first, second, third].flatMap((brands, f) =>
  brands.map(([name, category], i) => ({
    id: `l${f + 1}-${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
    name,
    category,
    color: colors[category],
    x: positions[i][0],
    y: positions[i][1],
    left: [1, 2, 4, 5, 7, 11, 12, 15, 18].includes(i),
    floorId: `l${f + 1}`,
  })),
);
export const upperAnchors = {
  l1: ['MASSIMO DUTTI', 'PANTALOONS', 'SHOPPERS STOP'],
  l2: ["bloomingdale's", 'H&M', 'NORDSTROM'],
  l3: ['ADIDAS', 'NIKE', 'LIFESTYLE'],
} as const;
